#!/bin/bash
REPO=aesirteam/docker-srs
TAG=v1

#stop docker process
sudo docker ps -a | grep $REPO:$TAG | awk '{print $1}' | while read cid
do
  sudo docker stop $cid
  sudo docker rm $cid
done

#remove docker image
sudo docker rmi $REPO:$TAG

git submodule update --init --recursive

#build docker image
sudo docker build -t=$REPO:$TAG .

#run docker image
#sudo docker run -d -v conf:/etc/srs/ -p 1935:1935 -p 1985:1985 $REPO:$TAG
