#!/bin/bash

usage() {
    echo "Usage: $0 <debian|raspbian>"
    exit 1
}

REPO=aesirteam/docker-srs-v3

if [ "$1" = "raspbian" ]; then
  TAG=$1
  DOCKERFILE="-f Dockerfile-raspbian"
elif [ "$1" = "debian" ]; then
  TAG=latest
else
   usage
   exit 1
fi

#stop docker process
sudo docker ps -a | grep $REPO:$TAG | awk '{print $1}' | while read cid
do
  sudo docker stop $cid
  sudo docker rm $cid
done

#remove docker image
sudo docker images -a | grep $REPO:$TAG | awk '{print $1}' | while read iid
do
  sudo docker rmi $iid
done

git submodule update --init --recursive

#build docker image
sudo docker build $DOCKERFILE -t=$REPO:$TAG .
